[package]
name = "f5restlib"
version = "0.0.1"
authors = ["FoxBoxPDX <foxboxpdx@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[dependencies]
hyper = '0.9.2'
serde = '0.7.5'
serde_json = '0.7.0'
