[package]
name = "f5restlib"
version = "0.0.1"
authors = ["FoxBoxPDX <foxboxpdx@gmail.com>"]
build = "build.rs"

[build-dependencies]
serde_codegen = "*"
syntex = "*"

[dependencies]
hyper = '0.9'
serde = '*'
serde_json = '*'
